# Generated by Django 3.1.4 on 2021-07-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_event_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community_event_manager',
            name='image',
            field=models.ImageField(default='test', upload_to='images'),
            preserve_default=False,
        ),
    ]
